### ISSUE TITLE
Handle tile flips

### ISSUE THREAD

**Issue by bcvery1** [bcvery1/tilepix#77]
Tiles can be flipped horizontally or/and vertically.  This alters the ID of the tile.  Reading this data is already handled, and the properties should already be set when tiles are decoded.  Need to render the tile in the flipped manner if the property is set.

**Comment by perber** [comment]
Hi, I will take the issue if you like.

**Comment by bcvery1** [comment]
You're very welcome to have a go at this issue - it was scheduled for 0.5.0, but I can pull it forward to 0.4.0
